/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as http from "../http.js";
import type * as otp_resend from "../otp/resend.js";
import type * as otp_verification from "../otp/verification.js";
import type * as pages_mutation from "../pages/mutation.js";
import type * as pages_query from "../pages/query.js";
import type * as password_reset_email from "../password_reset/email.js";
import type * as password_reset_otp from "../password_reset/otp.js";
import type * as shared_constants from "../shared/constants.js";
import type * as shared_mutation from "../shared/mutation.js";
import type * as user_query from "../user/query.js";
import type * as workspaces_mutation from "../workspaces/mutation.js";
import type * as workspaces_query from "../workspaces/query.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  http: typeof http;
  "otp/resend": typeof otp_resend;
  "otp/verification": typeof otp_verification;
  "pages/mutation": typeof pages_mutation;
  "pages/query": typeof pages_query;
  "password_reset/email": typeof password_reset_email;
  "password_reset/otp": typeof password_reset_otp;
  "shared/constants": typeof shared_constants;
  "shared/mutation": typeof shared_mutation;
  "user/query": typeof user_query;
  "workspaces/mutation": typeof workspaces_mutation;
  "workspaces/query": typeof workspaces_query;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
